In [1]:
pip install numpy


     ---------------------------------------- 0.0/61.0 kB ? eta -:--:--
     --------------------------------- ------ 51.2/61.0 kB 1.3 MB/s eta 0:00:01
     ---------------------------------------- 61.0/61.0 kB 1.1 MB/s eta 0:00:00
   ---------------------------------------- 0.0/15.8 MB ? eta -:--:--
   ---------------------------------------- 0.0/15.8 MB 1.9 MB/s eta 0:00:09
   ---------------------------------------- 0.1/15.8 MB 975.2 kB/s eta 0:00:17
   ---------------------------------------- 0.1/15.8 MB 930.9 kB/s eta 0:00:17
   ---------------------------------------- 0.1/15.8 MB 774.0 kB/s eta 0:00:21
   ---------------------------------------- 0.2/15.8 MB 807.1 kB/s eta 0:00:20
    --------------------------------------- 0.2/15.8 MB 778.2 kB/s eta 0:00:21
    --------------------------------------- 0.2/15.8 MB 719.7 kB/s eta 0:00:22
    --------------------------------------- 0.3/15.8 MB 768.0 kB/s eta 0:00:21
    --------------------------------------- 0.3/15.8 MB 754.8 kB/s 

ERROR: Could not install packages due to an OSError: [WinError 2] The system cannot find the file specified: 'C:\\Python310\\Scripts\\f2py.exe' -> 'C:\\Python310\\Scripts\\f2py.exe.deleteme'


[notice] A new release of pip is available: 23.3.2 -> 24.0
[notice] To update, run: python.exe -m pip install --upgrade pip


In [2]:
import numpy as np

In [4]:
list1=np.random.randint(1, 50, size=(10))
list1

array([43,  4, 40, 46,  5,  1, 42, 25, 23, 19])

In [5]:
list2=[1,2,3]
print('list2', type(list2))

list2 <class 'list'>


In [7]:
list1.size

10

In [8]:
list1.ndim

1

In [9]:
list1.dtype

dtype('int32')

In [10]:
random_array = np.random.rand(5, 2)

In [17]:
random_int_array = np.random.randint(10, 100, size=(2, 5,7,2))
random_int_array.shape

(2, 5, 7, 2)

In [18]:
list3=np.random.randint(1, 50, size=(10))

In [19]:
np.mean(list3)

32.1

In [22]:
list4=[5,1,4]
list5=[1,5,8]
list6=np.add(list4,list5)

In [23]:
np.mean(list6)

8.0

In [26]:
list7=np.random.randint(1, 100, size=(20))
list8=list7[list7>50]
list8

array([82, 54, 90, 77, 57, 67, 72, 90, 89, 88, 61, 96, 86])

In [34]:
list9=np.random.randint(1, 10, size=(20))
list9

array([2, 8, 1, 9, 3, 5, 3, 9, 6, 3, 7, 4, 4, 6, 3, 6, 1, 5, 8, 6])

In [33]:
np.random.shuffle(list9)
list9

array([4, 9, 2, 2, 9, 1, 1, 2, 4, 5, 1, 4, 5, 5, 1, 9, 8, 2, 9, 9])

In [35]:
index=np.random.randint(1,10,size(1))

NameError: name 'random' is not defined